[package]
name = "f"
version = "0.1.0"
authors = ["Kristian Freeman <kristian@kristianfreeman.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
structopt = "0.2.18"
sublime_fuzzy = "0.6.0"